//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderTable
    {
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int TotalAmount { get; set; }
        public int DiscountAmount { get; set; }
        public int PayableAmount { get; set; }
        public bool IsCompleted { get; set; }
        public int Quantity { get; set; }
        public System.DateTime orderDate { get; set; }
        public string PaymentType { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual orderTable orderTable1 { get; set; }
        public virtual orderTable orderTable2 { get; set; }
        public virtual Product Product { get; set; }
    }
}
