//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.orderTables = new HashSet<orderTable>();
        }
    
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Product Name Cannot be blank")]
        public string productName { get; set; }

        [Required(ErrorMessage = "SubCategory Cannot be blank")]
        public int SubCategoryId { get; set; }

        [Required(ErrorMessage = "ProductPrice Cannot be blank")]
        public int ProductPrice { get; set; }

        [Required(ErrorMessage = "Discount Cannot be blank")]
        public int Discount { get; set; }

        [Required(ErrorMessage = "ProductImage Cannot be blank")]
        public string ProductImage { get; set; }

        [Required(ErrorMessage = "Description Cannot be blank")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Quantity Cannot be blank")]
        public int Quantity { get; set; }

        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTable> orderTables { get; set; }
        public virtual subCategory subCategory { get; set; }
    }
}
