//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping()
        {
            this.orderTables = new HashSet<orderTable>();
        }

        public int ShippingId { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Address Cannot be blank")]
        public string Address { get; set; }

        [Required(ErrorMessage = "city Cannot be blank")]
        public string city { get; set; }

        [Required(ErrorMessage = "state Cannot be blank")]
        public string state { get; set; }

        [Required(ErrorMessage = "country Cannot be blank")]
        public string country { get; set; }

        [Required(ErrorMessage = "Pincode Cannot be blank")]
        public int Pincode { get; set; }

        [Required(ErrorMessage = "Name Cannot be blank")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Mobile Cannot be blank")]
        public string Mobile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTable> orderTables { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
