//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.Carts = new HashSet<Cart>();
            this.orderTables = new HashSet<orderTable>();
            this.Shippings = new HashSet<Shipping>();
        }

        public int UserId { get; set; }
        [Required(ErrorMessage ="FirstName Cannot be blank")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "LastName Cannot be blank")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "UserName Cannot be blank")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Password Cannot be blank")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Email Cannot be blank")]
        public string Email { get; set; }
        public System.DateTime AccountCreated { get; set; }
        public int RoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTable> orderTables { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping> Shippings { get; set; }
    }
}
